### ISSUE TITLE
Error when trying to run my program

### ISSUE THREAD

**Issue by Jimmay13** [remiomosowon/pyeasyga#3]
Greetings,

I am having trouble with a program I wrote and I was curious if you could help me.  I am getting an error message.

def create_individual(SimFrame):
    x1 = np.zeros(len(SimFrame[SimFrame['Position']=='C']))
    rdm = random.randint(0,len(SimFrame[SimFrame['Position']=='C'])-1)
    x1[rdm] = 1
    x2 = np.zeros(len(SimFrame[SimFrame['Position']=='PF']))
    rdm = random.sample(range(0,len(SimFrame[SimFrame['Position']=='PF'])-1),2)
    x2[rdm] = 1
    x3 = np.zeros(len(SimFrame[SimFrame['Position']=='PG']))
    rdm = random.sample(range(0,len(SimFrame[SimFrame['Position']=='PG'])-1),2)
    x3[rdm] = 1
    x4 = np.zeros(len(SimFrame[SimFrame['Position']=='SF']))
    rdm = random.sample(range(0,len(SimFrame[SimFrame['Position']=='SF'])-1),2)
    x4[rdm] = 1
    x5 = np.zeros(len(SimFrame[SimFrame['Position']=='SG']))
    rdm = random.sample(range(0,len(SimFrame[SimFrame['Position']=='SG'])-1),2)
    x5[rdm] = 1
    xt = np.append(x1,x2)
    xt = np.append(xt,x3)
    xt = np.append(xt,x4)
    xt = np.append(xt,x5)
    return xt

ga = pyeasyga.GeneticAlgorithm(SimFrame,
                               population_size=40,
                               generations=80,
                               elitism = True,
                               maximise_fitness= True)
ga.create_individual = create_individual

def fitness (individual,SimFrame):
    Total_Value, Total_Salary = 0, 0
    for selected, val, sal  in zip(individual,SimFrame['Value'],SimFrame['FD Sal']):
        if selected:
            Total_Value += val
            Total_Salary += sal
    if Total_Salary > 60000:
        Total_Value = 0
    return Total_Value

ga.fitness_function = fitness
ga.run()
print(ga.best_individual())

The error message I get is this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamesordaya/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/Users/jamesordaya/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/Users/jamesordaya/Desktop/titanic/SimulationWgaDK.py", line 84, in <module>
    ga.run()
  File "/anaconda3/lib/python3.6/site-packages/pyeasyga/pyeasyga.py", line 202, in run
    self.create_next_generation()
  File "/anaconda3/lib/python3.6/site-packages/pyeasyga/pyeasyga.py", line 193, in create_next_generation
    self.create_new_population()
  File "/anaconda3/lib/python3.6/site-packages/pyeasyga/pyeasyga.py", line 166, in create_new_population
    parent_1.genes, parent_2.genes)
  File "/anaconda3/lib/python3.6/site-packages/pyeasyga/pyeasyga.py", line 88, in crossover
    child_1 = parent_1[:index] + parent_2[index:]
ValueError: operands could not be broadcast together with shapes (55,) (9,) 

My data is too long to present.  If you have any questions, please ask away.

**Comment by Jimmay13** [comment]
NVM I solved the problem.  Individual was an array and not a list
