### ISSUE TITLE
"UnicodeDecodeError" occurred when "pip install pyeasyga"

### ISSUE THREAD

**Issue by chankane** [remiomosowon/pyeasyga#5]
```
Collecting pyeasyga
  Using cached https://files.pythonhosted.org/packages/3f/1b/d2834ca8e108806734a59579fe38a9fa1329f2527d622c43894c1c85a233/pyeasyga-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CLOUDU~1\AppData\Local\Temp\pip-install-ztw0b4w_\pyeasyga\setup.py", line 30, in <module>
        history = open('HISTORY.rst').read().replace('.. :changelog:', '')
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x99 in position 774: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CLOUDU~1\AppData\Local\Temp\pip-install-ztw0b4w_\pyeasyga\
```

**Comment by ctyeong** [comment]
same here.

Seems like the error occurs with Python3. 

I tried pip with Python2, and it worked.

**Comment by chankane** [comment]
Yes, I am using Python3.
Thank you for your help ctyeong!

**Comment by b-mi** [comment]
Why I cannot use python3?
